matrix:
    include:
        - name: "Linux-Py2"
          os: linux
          dist: xenial
          env:
            - MINICONDA=Miniconda2-latest-Linux-x86_64.sh
            - PYVER="--python=27"
        - name: "Linux-Py3"
          os: linux
          dist: xenial
          env:
            - MINICONDA=Miniconda3-latest-Linux-x86_64.sh
            - PYVER=""
        - name: "OsX-Py2"
          os: osx
          osx_image: xcode8
          env:
            - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"
            - MINICONDA=Miniconda3-latest-MacOSX-x86_64.sh
            - MACOSX_DEPLOYMENT_TARGET="10.9"
            - PYVER="--python=27"
        - name: "OsX-Py3"
          os: osx
          osx_image: xcode8
          env:
            - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"
            - MINICONDA=Miniconda3-latest-MacOSX-x86_64.sh
            - MACOSX_DEPLOYMENT_TARGET="10.9"
            - PYVER=""

install:
  - wget https://repo.continuum.io/miniconda/$MINICONDA -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda update --yes -q conda
  - conda install --yes conda-build
  # Useful for debugging any issues with conda
  - conda info -a
  - gcc -v
  - g++ -v

script:
  - conda build -c conda-forge $PYVER --override-channels conda-recipe
